version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "julia"
    directories:
      - "/"
      - "/docs"
      - "/test/NitroTestKit"
      - "/examples/mnist"
    schedule:
      interval: "weekly"
